/*******************************************************************************
 * 
 * This Function Create a new Insta Username Likes Data Sheet and Properties / Headers.
 * As a Child of Create Client Function
 * 
 */

const fs = require('fs');

const ciceroKeys = JSON.parse (fs.readFileSync('ciceroKey.json'));

//Google Spreadsheet
const { GoogleSpreadsheet } = require ('google-spreadsheet');
const { JWT } = require ('google-auth-library');

const googleAuth = new JWT({
  // env var values here are copied from service account credentials generated by google
  // see "Authentication" section in docs for more info
  email: ciceroKeys.client_email,
  key: ciceroKeys.private_key,
  scopes: ['https://www.googleapis.com/auth/spreadsheets'],
});

module.exports = {
    instaUserLikesHeaders: async function instaUserLikesHeaders(clientName){
        let response;

        //Insta Likes User DataBase Headers
        try {
            
            const instaLikesUsernameDoc= new GoogleSpreadsheet(ciceroKeys.dbKey.instaLikesUsernameID, googleAuth);//Google Authentication for instaLikes Username DB
            await instaLikesUsernameDoc.loadInfo(); // loads document properties and worksheets 
            
            let instaLikesUsernameSheet = await instaLikesUsernameDoc.addSheet({title : clientName});        
            await instaLikesUsernameSheet.resize({rowCount:1000 , columnCount : 1501});

            let headersRows =['SHORTCODE'];

            for (let i = 1; i < 1501; i++){
                headersRows.push('USER_'+i);
            }


            await instaLikesUsernameSheet.setHeaderRow(headersRows, 1);

            response = {
                data: 'Create Insta Official Data Sheet '+clientName,
                state : true,
                code : 200
            }

            return response;

        } catch (error) {

            response = {
                data: 'Error Create Insta Official Data Sheet',
                state : false,
                code : 303
            }           

            return response;
        }

  
    }
}