/*******************************************************************************
 * 
 * This Function Create a new Insta Official Data Sheet and Properties / Headers.
 * As a Child of Create Client Function
 * 
 */

const fs = require('fs');

const ciceroKeys = JSON.parse (fs.readFileSync('ciceroKey.json'));

//Google Spreadsheet
const { GoogleSpreadsheet } = require ('google-spreadsheet');
const { JWT } = require ('google-auth-library');

const googleAuth = new JWT({
  // env var values here are copied from service account credentials generated by google
  // see "Authentication" section in docs for more info
  email: ciceroKeys.client_email,
  key: ciceroKeys.private_key,
  scopes: ['https://www.googleapis.com/auth/spreadsheets'],
});

module.exports = {
    instaOfficialHeaders: async function instaOfficialHeaders(clientName){
 
        let response;

        //Insta Official DataBase Headers
        try {

            const instaOfficialDoc = new GoogleSpreadsheet(ciceroKeys.dbKey.instaOfficialID, googleAuth);//Google Authentication for InstaOfficial DB            
            await instaOfficialDoc.loadInfo(); // loads document properties and worksheets

            await instaOfficialDoc.addSheet({title : clientName, headerValues: ['TIMESTAMP', 'USER_ACCOUNT', 'SHORTCODE', 'ID', 'TYPE', 'CAPTION', 
                'COMMENT_COUNT', 'LIKE_COUNT', 'PLAY_COUNT']});
    
            response = {
                data: 'Create Insta Official Data Sheet '+clientName,
                state : true,
                code : 200
            }
                
            return response;
            
        } catch (error) {
            
            response = {
                data: 'Error Create Insta Official Data Sheet',
                state : false,
                code : 303
            }
            
            console.log(error);

            return response;
        }
    }
}