/*******************************************************************************
 * 
 * This Function Create a new Tiktok User Comments Data Sheet and Properties / Headers.
 * As a Child of Create Client Function
 * 
 */

const fs = require('fs');

const ciceroKeys = JSON.parse (fs.readFileSync('ciceroKey.json'));

//Google Spreadsheet
const { GoogleSpreadsheet } = require ('google-spreadsheet');
const { JWT } = require ('google-auth-library');

const googleAuth = new JWT({
  // env var values here are copied from service account credentials generated by google
  // see "Authentication" section in docs for more info
  email: ciceroKeys.client_email,
  key: ciceroKeys.private_key,
  scopes: ['https://www.googleapis.com/auth/spreadsheets'],
});

module.exports = {
    tiktokUserCommentsHeaders: async function tiktokUserCommentsHeaders(clientName){
        let response;

        //Tiktok Comments User DataBase Headers
        try {

            const tiktokCommentsUsernameDoc= new GoogleSpreadsheet(ciceroKeys.dbKey.tiktokCommentUsernameID, googleAuth);//Google Authentication for instaLikes Username DB
            await tiktokCommentsUsernameDoc.loadInfo(); // loads document properties and worksheets 

            let tiktokCommentsUsernameSheet = await tiktokCommentsUsernameDoc.addSheet({title : clientName});        
            await tiktokCommentsUsernameSheet.resize({rowCount:1000 , columnCount : 1501});

            let headersRows =['SHORTCODE'];

            for (let i = 1; i < 1501; i++){
                headersRows.push('USER_'+i);
            }

            await tiktokCommentsUsernameSheet.setHeaderRow(headersRows, 1);

            response = {
                data: 'Create Tiktok Comments User Data Sheet '+clientName,
                state : true,
                code : 200
            }

            return response;
            
        } catch (error) {

            response = {
                data: 'Error Create Tiktok Comments User Data Sheet',
                state : false,
                code : 303
            }

            return response;
        }

    }
}