const fs = require('fs');

const ciceroKeys = JSON.parse (fs.readFileSync('ciceroKey.json'));

//Google Spreadsheet
const { GoogleSpreadsheet } = require ('google-spreadsheet');
const { JWT } = require ('google-auth-library');

const googleAuth = new JWT({
  // env var values here are copied from service account credentials generated by google
  // see "Authentication" section in docs for more info
  email: ciceroKeys.client_email,
  key: ciceroKeys.private_key,
  scopes: ['https://www.googleapis.com/auth/spreadsheets'],
});

module.exports = {
    userDataBaseHeaders: async function userDataBaseHeaders(clientName){
        let response;
        //User DataBase Headers
        try {

            const userDoc = new GoogleSpreadsheet(ciceroKeys.dbKey.databaseID, googleAuth);//Google Auth
            userDoc.loadInfo;

            const userHeaderSheet = await userDoc.addSheet({ title: clientName, headerValues:['ID_KEY', 'NAMA', 'TITLE', 'DIVISI', 'JABATAN', 'STATUS', 
                'WHATSAPP', 'INSTA', 'TIKTOK']});

            response = {
                data: 'Create User Data Sheet '+clientName,
                state : true,
                code : 200
            }

            userDoc.delete;

            return response;

        } catch (error) {
            
            response = {
                data: 'Create User Data Sheet Error',
                state : false,
                code : 303
            }

            return response;
        }
    }
}