const fs = require('fs');

//Google Spreadsheet
const { GoogleSpreadsheet } = require('google-spreadsheet');
const { JWT } = require ('google-auth-library');

const googleCreds = JSON.parse(fs.readFileSync('./database/ciceroKey.json'));

const googleAuth = new JWT({
  // env var values here are copied from service account credentials generated by google
  // see "Authentication" section in docs for more info
  email: googleCreds.client_email,
  key: googleCreds.private_key,
  scopes: ['https://www.googleapis.com/auth/spreadsheets'],
});

module.exports = {
  
  //New Client Database by Organizations Source Functions
  newClientOrg: async function newClientOrg(sheetName, sourceID, filesID){

    const sourceX = sourceID.split('/').pop(); //Get Last Segment of Links
    
    const targetDoc = new GoogleSpreadsheet(filesID, googleAuth); //Google Auth

    try {
      //Insert New Sheet
      const targetSheet = await targetDoc.addSheet({ title: sheetName, headerValues:['ID_KEY', 'NAMA', 'TITLE', 'DIVISI', 'JABATAN', 'STATUS', 'WHATSAPP', 'INSTA', 'TIKTOK'] });
      console.log(targetSheet.title);

      const sourceDoc = new GoogleSpreadsheet(sourceX, googleAuth); //Google Auth
      await sourceDoc.loadInfo(); // loads document properties and worksheets

      const sheetSource = sourceDoc.sheetsByTitle[sheetName]; //Get Source Sheet Documents by Title
      const rowsSource = await sheetSource.getRows(); //Get Sheet data By Rows
      
      await targetDoc.loadInfo(); // loads document properties and worksheets
      const sheetTarget = targetDoc.sheetsByTitle[sheetName]; //Get Target Sheet Documents by Title

      var i = 0;  //  set your counter to 0

      function pushDataOrg() { //  create a loop function
        setTimeout(function() { //  call a 2s setTimeout when the loop is called
          sheetTarget.addRow({ID_KEY: rowsSource[i].get('NRP'), NAMA: rowsSource[i].get('NAMA'), TITLE: rowsSource[i].get('PANGKAT'), DIVISI: rowsSource[i].get('SATFUNG'), JABATAN: rowsSource[i].get('JABATAN'), STATUS: true, WHATSAPP: rowsSource[i].get('WHATSAPP'), INSTA: rowsSource[i].get('IG1'), TIKTOK: rowsSource[i].get('TIKTOK')});
          //  post data
          i++;  //  increment the counter
          if (i < rowsSource.length) {  //  if the counter < rowsSource.length, call the loop function
            pushDataOrg(); //  again which will trigger another 
          } else {
            console.log("All Data Transfered");
          };
        }, 2000)
      }
      //initiate
      pushDataOrg();
    } catch (error) {
      //if sheet name is exist
      console.log('Sheet Exist');
    }
  },

  //New Client Database by Company Source Functions  
  newClientCom: async function newClientCom(sheetName, sourceID, filesID){

    const sourceX = sourceID.split('/').pop();      //Get Last Segment of Links
    const targetDoc = new GoogleSpreadsheet(filesID, googleAuth);//Google Auth

    try {
      //Insert New Sheet
      const targetSheet = await targetDoc.addSheet({ title: sheetName, headerValues:['ID_KEY', 'NAMA', 'TITLE', 'DIVISI', 'JABATAN', 'STATUS', 'WHATSAPP', 'INSTA', 'TIKTOK'] });
      console.log(targetSheet.title);

      const sourceDoc = new GoogleSpreadsheet(sourceX, googleAuth); //Google Auth
      await sourceDoc.loadInfo(); // loads document properties and worksheets

      const sheetSource = sourceDoc.sheetsByTitle[sheetName]; //Get Source Sheet Documents by Title
      const rowsSource = await sheetSource.getRows(); // loads document properties and worksheets
      
      await targetDoc.loadInfo(); // loads document properties and worksheets
      const sheetTarget = targetDoc.sheetsByTitle[sheetName];//Get Target Sheet Documents by Title

      var i = 0;  //  set your counter to 0

      function pushDataCom() { //  create a loop function
        setTimeout(function() { //  call a 2s setTimeout when the loop is called
          sheetTarget.addRow({ID_KEY: rowsSource[i].get('ID_KEY'), NAMA: rowsSource[i].get('NAMA'), TITLE: null, DIVISI: rowsSource[i].get('DIVISI'), JABATAN: rowsSource[i].get('JABATAN'), STATUS: true, WHATSAPP: rowsSource[i].get('WHATSAPP'), INSTA: rowsSource[i].get('INSTA'), TIKTOK: rowsSource[i].get('TIKTOK')});
          //  post data
          i++;  //  increment the counter
          if (i < rowsSource.length) {  //  if the counter < rowsSource.length, call the loop function
            pushDataCom();  //again which will trigger another 
          } else {
            console.log("All Data Transfered");
          };
        }, 2000)
      }
      //initiate
      pushDataCom();
    } catch (error) {
      //if sheet name is exist
      console.log('Sheet Exist');
    }
  },

  //Add New User to Client Data Base Functions  
  addUser: async function addUser(sheetName, idKey, userName, userDiv, userJab, userTitle, filesID){
    const targetDoc = new GoogleSpreadsheet(filesID, googleAuth);//Google Auth
    try {
      //Insert New Sheet
      await targetDoc.loadInfo(); // loads document properties and worksheets
      const sheetTarget = targetDoc.sheetsByTitle[sheetName];

      await targetDoc.loadInfo(); // loads document properties and worksheets
      const rowsData = await sheetTarget.getRows();
      
      let divisiList = [];

      //Collect Divisi List String
      for (let i = 0; i < rowsData.length; i++){
        if(!divisiList.includes(rowsData[i].get('DIVISI'))){
          divisiList.push(rowsData[i].get('DIVISI'));
        }
      }
      if(divisiList.includes(userDiv)){
        //Get Target Sheet Documents by Title
        sheetTarget.addRow({ID_KEY: idKey, NAMA: userName, TITLE: userTitle, DIVISI: userDiv, JABATAN: userJab, STATUS: true});

        console.log('Success Input Data');
      } else {
        console.log('Divisi Tidak Terdaftar');
      }
    } catch (error) {
      //if sheet name is exist
      console.log(error);
    }
  },
  //Edit User Divisi to Client Data Base Functions  
  editDivisi: async function editDivisi(sheetName, idKey, userDiv, filesID){
    const targetDoc = new GoogleSpreadsheet(filesID, googleAuth);//Google Auth
    try {
      //Insert New Sheet
      await targetDoc.loadInfo(); // loads document properties and worksheets
      const sheetTarget = targetDoc.sheetsByTitle[sheetName];

      await targetDoc.loadInfo(); // loads document properties and worksheets
      const rowsData = await sheetTarget.getRows();

      let divisiList = [];

      //Collect Divisi List String
      for (let i = 0; i < rowsData.length; i++){
        if(!divisiList.includes(rowsData[i].get('DIVISI'))){
          divisiList.push(rowsData[i].get('DIVISI'));
        }
      }

      let isDataExist = false;

      if (divisiList.includes(userDiv)){
        for (let ii = 0; ii < rowsData.length; ii++){
          if (rowsData[ii].get('ID_KEY') === idKey){
            console.log(rowsData[ii].get('ID_KEY'));

            isDataExist = true;
            rowsData[ii].set('DIVISI', userDiv); // Update Divisi Value
            await rowsData[ii].save(); //save update
          }
        }

        if(!isDataExist){
          console.log('User Data with delegated ID_KEY Doesn\'t Exist');
        }
      } else {
        console.log('Divisi Unregsitered');
      }
    } catch (error) {
      //if sheet name is exist
      console.log('Sheet Exist');
    }
  },
};