const fs = require('fs');
const axios = require('axios');

//Google Spreadsheet
const { GoogleSpreadsheet } = require ('google-spreadsheet');
const { JWT } = require ('google-auth-library');

const googleCreds = JSON.parse (fs.readFileSync('ciceroKey.json'));
const instaKey = JSON.parse (fs.readFileSync('instaKey.json'));

const googleAuth = new JWT({
  // env var values here are copied from service account credentials generated by google
  // see "Authentication" section in docs for more info
  email: googleCreds.client_email,
  key: googleCreds.private_key,
  scopes: ['https://www.googleapis.com/auth/spreadsheets'],
});

const headers = {
  'x-cache-control': 'no-cache',
  'x-rapidapi-key': instaKey.instakeyAPI,
  'x-rapidapi-host': instaKey.instahostAPI
}

async function instaPostInfoAPI(key){
  //Insta Post API
  let options = {
    method: 'GET',
    url: instaKey.instapostInfo,
    params: {
      code_or_id_or_url: key,
      include_insights: 'true'    },
    headers: headers
  };

  try {
    let response = await axios.request(options);
    return response.data;
  } catch (error) {
console.log(error);
  }
}

module.exports = {

  waStoryInsta: async function waStoryInsta(whatsapp, instalink, userClientID, clientID, waStoryID){

    const userClientDoc = new GoogleSpreadsheet(userClientID, googleAuth);//Google Authentication for user client DB
    await userClientDoc.loadInfo(); // loads document properties and worksheets

    const clientDoc = new GoogleSpreadsheet(clientID, googleAuth);//Google Authentication for client DB
    await clientDoc.loadInfo(); // loads document properties and worksheets

//    const waStoryDoc = new GoogleSpreadsheet(waStoryID, googleAuth);//Google Authentication for client DB
//    await waStoryDoc.loadInfo(); // loads document properties and worksheets
    
    let insta = instalink[0];


    if(insta.includes('instagram.com')){

      let instaUrl = insta.split('?')[0];

      let shortcode = instaUrl.split('/');
      
      let instaPost = await instaPostInfoAPI(shortcode.at(-2));

      console.log(instaPost);
      let instaOfficial = instaPost.data.user.username;

      const clientDataSheet = clientDoc.sheetsByTitle['ClientData'];
      const rowsClientData = await clientDataSheet.getRows();

      let hasSheetName = false;
      let sheetName;
      
      for (let i = 0; i < rowsClientData.length; i++){
        if (rowsClientData[i].get('INSTAGRAM') === instaOfficial){
          hasSheetName = true;
          sheetName = rowsClientData[i].get('CLIENT_ID');
        }
      }
      
      if(hasSheetName){

        let userClientSheet = await userClientDoc.sheetsByTitle[sheetName];
        let userClientData = await userClientSheet.getRows();
        let hasUser = false;

        for (let ii = 0; ii < userClientData.length; ii++){
          if(userClientData[ii].get('WHATSAPP') === whatsapp.replaceAll("@c.us", "")){
            hasUser = true;
          }
        }

        if(hasUser){
          
          return 'Terimakasih sudah berpartisipasi meningkatkan Engagement Akun Instagram Kita';

        } else {

          return 'Number not recorded';
        }
      } else {
        console.log('No Client ID Attached to Insta Accounts');
      }
    }//if(url.includes...
  }//waStoryInsta....
}//module export....