const fs = require('fs');

//Google Spreadsheet
const { GoogleSpreadsheet } = require ('google-spreadsheet');
const { JWT } = require ('google-auth-library');

const googleCreds = JSON.parse (fs.readFileSync('ciceroKey.json'));

const googleAuth = new JWT({
  // env var values here are copied from service account credentials generated by google
  // see "Authentication" section in docs for more info
  email: googleCreds.client_email,
  key: googleCreds.private_key,
  scopes: ['https://www.googleapis.com/auth/spreadsheets'],
});

module.exports = {
    //Set Client State to Database Client ID  
    setClientState: async function setClientState(sheetName, state, filesID){

    const targetDoc = new GoogleSpreadsheet(filesID, googleAuth);//Google Auth
    
    try {
        //Insert New Sheet
        await targetDoc.loadInfo(); // loads document properties and worksheets
        const sheetTarget = targetDoc.sheetsByTitle['ClientData'];
        const clientData = await sheetTarget.getRows();

        let isDataExist = false;

        for (let i = 0; i < clientData.length; i++){
        if (clientData[i].get('CLIENT_ID') === sheetName){
            isDataExist = true;
            clientData[i].assign({STATUS: state});; // Updae State Value
            await clientData[i].save(); //save update

            let responseData = {
            message : 'Client State with Client_ID : '+sheetName+' set status to : '+state,
            state : true,
            code : 1
            }
        
            console.log('Return Success');

            targetDoc.delete;

            return responseData;
        }
        }
        if(!isDataExist){

        let responseData = {
            message : 'No Data with Client_ID : '+sheetName,
            state : true,
            code : 1
        }
        
        console.log('Return Success');

        targetDoc.delete;

        return responseData;
        
        }
    } catch (error) {
        
        let responseData = {
        message : error,
        state : false,
        code : 0
        }

        console.log('Return Success');

        targetDoc.delete;

        return responseData;
    }
    },  
}