import { readFileSync } from 'fs';
import { GoogleSpreadsheet } from 'google-spreadsheet';

const ciceroKey = JSON.parse (readFileSync('ciceroKey.json'));
import { JWT } from 'google-auth-library';

const googleAuth = new JWT({
  // env var values here are copied from service account credentials generated by google
  // see "Authentication" section in docs for more info
  email: ciceroKey.client_email,
  key: ciceroKey.private_key,
  scopes: ['https://www.googleapis.com/auth/spreadsheets'],
});

export async function postRowData(responseData){

}